# Generated by Django 4.0.4 on 2022-05-07 02:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('name_category', models.CharField(max_length=255, verbose_name='Nombre de Categoria de Habilidades')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'ordering': ['name_category'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de Habilidad')),
                ('level', models.IntegerField(choices=[(0, 'None'), (1, 'Basic'), (1, 'Intermedium'), (2, 'Advanced'), (3, 'Native')], default=0, verbose_name='Nivel de Habilidad')),
                ('category_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.categoryskill')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
