# Generated by Django 4.0.4 on 2022-05-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_categoryskill_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryskill',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category_skill',
        ),
        migrations.AddField(
            model_name='categoryskill',
            name='profiles',
            field=models.ManyToManyField(to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category_skills',
            field=models.ManyToManyField(to='profiles.categoryskill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Basic'), (2, 'Intermedium'), (3, 'Advanced'), (4, 'Native')], default=0, verbose_name='Nivel de Habilidad'),
        ),
    ]
