# Generated by Django 4.0.4 on 2022-05-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_categoryskill_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryskill',
            old_name='profiles',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='category_skills',
            new_name='category_skill',
        ),
    ]
