version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker build .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag python:3.9 akey96/resume-manager:v1.0
          docker push akey96/resume-manager:v1.0
  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 service/manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
  deploy:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: |
          chmod 400 llave-produccion.pem
          echo '18.220.194.151 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHb315V+LulCEFVaLLQ/y7Rrgc4ATN5YQxWbxD4zt1OUjsDEUglQzslyzQYigMdMF++yboQWRfuCrgkr7kg1uEa5IpHPip8asKcJJRVnk4QlzId6KS7nTkHX3OIKvZ/G0ZmdUGS0Vfo/ixACz5f3XRGkUxs3zJ8e/aC42uReB4efxvAlLzoY3lU5USEMuh49+xRdcf0nTXHyrZE/FKjgPWIpr+L0gF7X79Tq/o68Hmue90h+F2CKpijeIXo43EgFeZ8ER08qpckMqrI5AHqIqeXiZObFO+Lt7aNRuPOMsbTmaPyO6LdC/quOwzUPfMtxeK/s+cHc7z4J+5YAeZHrEBXxVMhhn41A5rPjYKZpax/XrQQq4gzqPyxGzX4mchvdhHfKN47gC41D0rZvNqU5kJwO59sBAaMRx/mJPDkkAlZVa8AgHTkpvbhX48rQ8U5NeaedhaSH63oTsdP7yMh/ohV3NfwKxkFgOf2hSwjYQqOs9mVXTbykOySl6SHOszwvE=' >> ~/.ssh/known_hosts
          ssh -i llave-produccion.pem ubuntu@18.220.194.151 <<'ENDSSH'
          cd resume-manager
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker pull akey96/resume-manager:v1.0
          sudo docker-compose up -d
          ENDSSH
workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              ignore: develop
      - build:
          filters:
            branches:
              ignore: develop
          requires:
            - test
      - deploy:
          filters:
            branches:
              only: develop
